### ISSUE TITLE
VnV Plan pre-review

### ISSUE THREAD

**Issue by adrian-soch** [adrian-soch/attitude_check#10]
**Describe the request**
Hi @smiths, if you have time, can you please check out my VnV Plan draft? Thank you

**List the files**

- [VnV plan](https://github.com/adrian-soch/attitude_check/blob/698b9e841711281bf6cbea6c67254ae9cc98f6c5/docs/VnVPlan/VnVPlan.pdf)

**Comment by smiths** [comment]
Feedback:

- who is going to do the SRS verification?  The checklist is a good idea, but what is required to check an item is ambiguous.
- similar comments for the design verification (we do create a few high level documents: the uses hierarchy and the decomposition by secrets tree)
- nice to see specific tools in 4.5
- T1 doesn't have a specific test - unless that is what it is in the unlabelled table?
- the Outputs are not specific enough in the table under T2 (and elsewhere).  What is the ground truth?  How is it found?  How is RMSE calculated?  What is the tolerance?
- you have confused usability (for users of the tool) with understandability (for developers)
- the tests for understandability aren't specific

I'll stop my review here.  Good start.  The overall comment is that you should strive to be more specific.
