### ISSUE TITLE
VnV Plan: Review Request 

### ISSUE THREAD

**Issue by adrian-soch** [adrian-soch/attitude_check#28]
**Describe the request**
Hi @smiths the VnV Plan for Attitude Check is ready for evaluation.

**List the files**

- [VnV Plan](https://github.com/adrian-soch/attitude_check/blob/361e36cb05019e83486cc3b9324a0a69529dde2f/docs/VnVPlan/VnVPlan.pdf)

Thank you

**Comment by smiths** [comment]
@adrian-soch have you created issues for your domain and secondary reviewers?

**Comment by smiths** [comment]
[Adrian_VnVPlan.pdf](https://github.com/adrian-soch/attitude_check/files/14566708/Adrian_VnVPlan.pdf)
