### ISSUE TITLE
VnV Review

### ISSUE THREAD

**Issue by adrian-soch** [adrian-soch/attitude_check#29]
**Describe the request**
Hey @cer-hunter its review timeeee

**List the files**

- [VnV](https://github.com/adrian-soch/attitude_check/blob/361e36cb05019e83486cc3b9324a0a69529dde2f/docs/VnVPlan/VnVPlan.pdf)

**Comment by cer-hunter** [comment]
Hey Adrian, great VnV Plan! Couldn't find many major issues, all my comments are in issues #36, #37, #38, #39, #40
