### ISSUE TITLE
Pre-presentation review

### ISSUE THREAD

**Issue by adrian-soch** [adrian-soch/attitude_check#5]
**Describe the request**
@smiths, you mentioned that you would like to see the presentations before class. I have uploaded it here.

- [SRS Presentation](https://github.com/adrian-soch/attitude_check/blob/16b1a59d3ccb9840e3665e4804fd453d45f4431c/docs/Presentations/cas741_srs.pdf)

**Comment by smiths** [comment]
Thank you @adrian-soch for sharing.  Some quick feedback in case we run out of time tomorrow:

- don't spend too much time on the table of symbols in the presentation (time will go fast and you want as much time as possible for the theoretical model)
- assumptions in the scope section seem good
- the first system constraint seems like two nonfunctional requirement for performance in speed and memory - system constraints are design decisions that are made for you - the performance isn't a design decision but a constraint - if you were constrained to use a specific piece of hardware that would be a constraint
- the second system constraint isn't really a constraint either - it isn't a design decision; it sounds like another nonfunctional requirement, or maybe the same one.  To be unambiguous, you need to say what resources are constrained
- for the physical system, models are not physical systems; it looks like you are partially confusing physical systems and theoretical models
- you haven't covered the "good stuff".  What are the theoretical models.  What are the calculations?  How do you turn measurements into the attitude estimate?  It is noisy data, so do you need a theoretical model for regression?
-
