### ISSUE TITLE
Usage of Ambiguous Symbols Without Reference

### ISSUE THREAD

**Issue by rnorouziani** [adrian-soch/attitude_check#51]
Throughout the document, there are instances where symbols and terms are used that may not be clear to all readers (e.g., ∆t, Eb, γ). These symbols are presumably defined in the SRS, but there are no direct references or hyperlinks to their definitions.

**Comment by adrian-soch** [comment]
It's briefly mentioned in the symbols section that symbols are defined in SRS. However, you are correct, there is no direct referencing - but I'm just going to assume the reader will look at the SRS if they are confused.
