### ISSUE TITLE
MG Module Hierarchy Section 5

### ISSUE THREAD

**Issue by cer-hunter** [adrian-soch/attitude_check#56]
I thought it was very interesting you didn't include a hardware-hiding module, considering your project is probably one with the most amount of hardware involvement since you're using an Arduino. Is there any specific reason you don't include one? Is the idea that your project actual _is_ the hardware-hiding for whatever the end use of the measurement would be? If this is the case maybe that should be noted somewhere, only since I think it would be useful information (or honestly I can see an argument for still including it in the hierarchy as like the top-level module since the entire project is hardware-hiding). Again just something to think about.

[MG](https://github.com/adrian-soch/attitude_check/blob/b022d9a4b8028ba3e22e967fc0e488347e53ad2e/docs/Design/SoftArchitecture/MG.pdf)

**Comment by adrian-soch** [comment]
See #73
