### ISSUE TITLE
MG Input Module Section 7.1.1 

### ISSUE THREAD

**Issue by cer-hunter** [adrian-soch/attitude_check#57]
Reading over the Input module, the secret reminded me that the input data constraints you are using the module to hide are definitely subject to change based on the sensor being used. I think "The constraints on the input" should probably be added to the list of anticipated changes.

[MG](https://github.com/adrian-soch/attitude_check/blob/b022d9a4b8028ba3e22e967fc0e488347e53ad2e/docs/Design/SoftArchitecture/MG.pdf)

**Comment by adrian-soch** [comment]
See #73
