### ISSUE TITLE
MIS Value Error (General)

### ISSUE THREAD

**Issue by cer-hunter** [adrian-soch/attitude_check#59]
Just something to consider, I know sometimes it may be useful to define once what exactly you mean by ValueError (I know it's likely outside the range of permissible input/output values or potentially a math error like overflow or something but defining it once wouldn't hurt).

[MIS](https://github.com/adrian-soch/attitude_check/blob/b022d9a4b8028ba3e22e967fc0e488347e53ad2e/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by adrian-soch** [comment]
See #73
