### ISSUE TITLE
Enhancing MIS and MG Documents with Hyperlinks

### ISSUE THREAD

**Issue by tanya-jp** [adrian-soch/attitude_check#65]
In both the MIS and MG documents, there are references to several websites, complete with the URLs provided in plain text. To enhance the user experience and facilitate easier access to these resources, it would be beneficial to convert these URLs into clickable hyperlinks. This would make accessing extra information more convenient and improve the document's user-friendliness.

**Comment by adrian-soch** [comment]
If you view the PDF in GitHub, the links don't work. When I download the file, it looks like they are functional.
