### ISSUE TITLE
SRS Evaluation

### ISSUE THREAD

**Issue by adrian-soch** [adrian-soch/attitude_check#7]
**Describe the request**
The SRS is ready for evaluation.

**List the files**

- [SRS](https://github.com/adrian-soch/attitude_check/blob/7c8cd7387ab120dd1267b56902499314c696e42b/docs/SRS/SRS.pdf)

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[AdrianSochaniwsky_SRS.pdf](https://github.com/adrian-soch/attitude_check/files/14389466/AdrianSochaniwsky_SRS.pdf)
